backend:
  name: git-gateway
  branch: main
  identity_url: "https://auth.decapbridge.com/sites/4e06c405-5a7e-4b42-b5ef-75422ec79166"
  gateway_url: "https://gateway.decapbridge.com"

site_url: https://luxuryhouse.pages.dev
logo_url: https://decapbridge.com/decapcms-with-bridge.svg

media_folder: "img"
public_folder: "/img"

collections:
  - name: "landing"
    label: "Contenido de la Landing"
    files:
      - name: "inicio"
        label: "Página Principal"
        file: "content/data.json"
        fields:
          - name: "hero"
            label: "Sección Hero"
            widget: "object"
            fields:
              - {label: "Etiqueta", name: "etiqueta", widget: "string"}
              - {label: "Título Principal (Soporta HTML)", name: "titulo", widget: "string"}
              - {label: "Descripción", name: "descripcion", widget: "text"}
              - {label: "Imagen de Fondo", name: "imagen_fondo", widget: "image"}
              - {label: "Texto Botón Principal", name: "boton_primario_texto", widget: "string"}
              - {label: "Enlace Botón Principal", name: "boton_primario_link", widget: "string"}
              - {label: "Texto Botón Secundario", name: "boton_secundario_texto", widget: "string"}
              - {label: "Enlace Botón Secundario", name: "boton_secundario_link", widget: "string"}
